### ISSUE TITLE
На openapi@alor.ru не проходит e-mail

### ISSUE THREAD

**Issue by toyan** [cia76/AlorPy#3]
На openapi@alor.ru не проходит e-mail, возвращается с сообщением:

Original-Recipient: rfc822;[openapi@alor.ru](mailto:openapi@alor.ru)
Final-Recipient: rfc822;[Nazarov@alor.ru](mailto:Nazarov@alor.ru)
Action: failed

**Comment by cia76** [comment]
Попробуйте сделать запрос в Telegram на https://t.me/AlorOpenAPI
